name: Delete release
on:
  workflow_dispatch:

jobs:
  deletion:
    name: delete
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove
        run: |
          gh release list --limit 100 -R Kosette/geoip | ForEach-Object { $_.Split("`t")[2] } | ForEach-Object { gh release delete --cleanup-tag -R Kosette/geoip -y $_ }
      
